

var qfilename = new Array();
var ix = 0;
qfilename[ix] = "authors/eric_abrahamson_and_david_h_freeman/a_perfect_mess_the_hidden_benefits_of_disorder/keep_creating_throughout_the_construction_process.html";
ix++;
qfilename[ix] = "authors/ansel_adams/unknown/fuzzy_concept.html";
ix++;
qfilename[ix] = "authors/margery_allingham/dancers_in_mourning/a_dark_procession.html";
ix++;
qfilename[ix] = "authors/margery_allingham/dancers_in_mourning/occasions_when_the_intellect_retires_gracefully.html";
ix++;
qfilename[ix] = "authors/margery_allingham/dancers_in_mourning/the_only_sign_of_mental_activity.html";
ix++;
qfilename[ix] = "authors/margery_allingham/dancers_in_mourning/the_sanctity_and_importance_of_sudden_death.html";
ix++;
qfilename[ix] = "authors/margery_allingham/the_tiger_in_the_smoke/merely_thoroughly_outrageous.html";
ix++;
qfilename[ix] = "authors/chris_argyris_and_donald_schn/theory_in_practice_increasing_personal_effectiveness/model_ii_decisionmaking.html";
ix++;
qfilename[ix] = "authors/chris_argyris_and_donald_schn/theory_in_practice_increasing_personal_effectiveness/model_ii_values.html";
ix++;
qfilename[ix] = "authors/aristotle/unknown/entertain_a_thought.html";
ix++;
qfilename[ix] = "authors/angeles_arrien/the_fourfold_way/the_fourfold_way.html";
ix++;
qfilename[ix] = "authors/angeles_arrien/the_fourfold_way/the_fourfold_way_1.html";
ix++;
qfilename[ix] = "authors/robert_d_austin/measuring_and_managing_performance_in_organizations/cockpits_with_instruments_controlled_by_gremlins.html";
ix++;
qfilename[ix] = "authors/rob_austin_and_lee_devin/artful_making_what_managers_need_to_know_about_how_artists_work/artful_making.html";
ix++;
qfilename[ix] = "authors/joseph_l_badaracco_jr/leading_quietly_an_unorthodox_guide_to_doing_the_right_thing/careful_thoughtful_small_practical_efforts.html";
ix++;
qfilename[ix] = "authors/don_beck_and_chris_cowan/spiral_dynamics_mastering_values_leadership_and_change/ancient_ethnic_sores_belching_fire.html";
ix++;
qfilename[ix] = "authors/scott_berkun/the_myths_of_innovation/real_creation_is_sloppy.html";
ix++;
qfilename[ix] = "authors/isaiah_berlin/the_hedgehog_and_the_fox/the_hedgehog_and_the_fox.html";
ix++;
qfilename[ix] = "authors/william_blake/unknown/art_science_and_empire.html";
ix++;
qfilename[ix] = "authors/william_blake/unknown/expectations_of_holiness.html";
ix++;
qfilename[ix] = "authors/william_blake/unknown/minute_particulars.html";
ix++;
qfilename[ix] = "authors/william_blake/the_portable_william_blake/to_see_a_world_in_a_grain_of_sand.html";
ix++;
qfilename[ix] = "authors/derek_bok/unknown/cost_of_education.html";
ix++;
qfilename[ix] = "authors/nathaniel_s_borenstein/programming_as_if_people_mattered_friendly_programs_software_engineering_and_other_noble_delusions/judgments_of_users.html";
ix++;
qfilename[ix] = "authors/joe_boyd/white_bicycles_making_music_in_the_1960s/a_sailors_life.html";
ix++;
qfilename[ix] = "authors/joe_boyd/white_bicycles_making_music_in_the_1960s/chaos_and_mediocrity.html";
ix++;
qfilename[ix] = "authors/joe_boyd/white_bicycles_making_music_in_the_1960s/countercultures_own_values_and_aesthetics_decayed.html";
ix++;
qfilename[ix] = "authors/joe_boyd/white_bicycles_making_music_in_the_1960s/dylan_at_newport_in_1965.html";
ix++;
qfilename[ix] = "authors/joe_boyd/white_bicycles_making_music_in_the_1960s/history_as_postmodern_collage.html";
ix++;
qfilename[ix] = "authors/joe_boyd/white_bicycles_making_music_in_the_1960s/little_i_recognized_as_music.html";
ix++;
qfilename[ix] = "authors/joe_boyd/white_bicycles_making_music_in_the_1960s/never_knew_cocaine_to_improve_anything.html";
ix++;
qfilename[ix] = "authors/joe_boyd/white_bicycles_making_music_in_the_1960s/records_we_made_together_in_the_sixties.html";
ix++;
qfilename[ix] = "authors/joe_boyd/white_bicycles_making_music_in_the_1960s/sixties_surpluses_of_money_and_time.html";
ix++;
qfilename[ix] = "authors/joe_boyd/white_bicycles_making_music_in_the_1960s/southeast_london_adaption_of_the_excello_style.html";
ix++;
qfilename[ix] = "authors/joe_boyd/white_bicycles_making_music_in_the_1960s/tiny_dead_recording_spaces.html";
ix++;
qfilename[ix] = "authors/joe_boyd/white_bicycles_making_music_in_the_1960s/twoinch_sixteentrack_recording.html";
ix++;
qfilename[ix] = "authors/george_brackett/the_elements_of_java_style/principle_of_least_astonishment.html";
ix++;
qfilename[ix] = "authors/wernher_von_braun/unknown/one_test_result.html";
ix++;
qfilename[ix] = "authors/bertolt_brecht/unknown/art_is_a_hammer.html";
ix++;
qfilename[ix] = "authors/fred_brooks/the_mythical_manmonth_essays_on_software_engineering/conceptual_integrity.html";
ix++;
qfilename[ix] = "authors/william_j_brown_hays_w_mccormick_iii_and_scott_w_thomas/antipatterns_and_patterns_in_software_configuration_management/drivethrough_coding.html";
ix++;
qfilename[ix] = "authors/william_j_brown_hays_w_mccormick_iii_and_scott_w_thomas/antipatterns_and_patterns_in_software_configuration_management/nirvana_antipattern.html";
ix++;
qfilename[ix] = "authors/william_jennings_bryan/democratic_national_convention/two_ideas_of_government.html";
ix++;
qfilename[ix] = "authors/marcus_buckingham_and_curt_coffman/first_break_all_the_rules_what_the_worlds_greatest_managers_do_differently/focus_on_high_performers.html";
ix++;
qfilename[ix] = "authors/albert_camus/unknown/work_soul_and_life.html";
ix++;
qfilename[ix] = "authors/albert_camus/lyrical_and_critical_essays/an_invincible_summer.html";
ix++;
qfilename[ix] = "authors/michael_chabon/keynote_at_eisner_awards/a_mind_is_blown.html";
ix++;
qfilename[ix] = "authors/raymond_chandler/the_simple_art_of_murder/down_these_mean_streets.html";
ix++;
qfilename[ix] = "authors/raymond_chandler/the_simple_art_of_murder/vital_and_significant_forms_of_art.html";
ix++;
qfilename[ix] = "authors/winston_churchill/unknown/democracy_is_worst_form_of_government.html";
ix++;
qfilename[ix] = "authors/alistair_cockburn/agile_software_development/system_architects_as_storytellers.html";
ix++;
qfilename[ix] = "authors/larry_constantine_and_lucy_lockwood/software_for_use_a_practical_guide_to_the_models_and_methods_of_usagecentered_design/prototyping_no_substitute_for_analysis_and_design.html";
ix++;
qfilename[ix] = "authors/larry_constantine_and_lucy_lockwood/software_for_use_a_practical_guide_to_the_models_and_methods_of_usagecentered_design/system_simplification.html";
ix++;
qfilename[ix] = "authors/larry_constantine_and_lucy_lockwood/software_for_use_a_practical_guide_to_the_models_and_methods_of_usagecentered_design/user_interface_architectures.html";
ix++;
qfilename[ix] = "authors/alan_m_davis/201_principles_of_software_development/difficulty_of_requirements_discovery.html";
ix++;
qfilename[ix] = "authors/alan_m_davis/201_principles_of_software_development/multiple_design_approaches.html";
ix++;
qfilename[ix] = "authors/alan_m_davis/just_enough_requirements_management_where_software_development_meets_marketing/just_enough_requirements.html";
ix++;
qfilename[ix] = "authors/alan_m_davis/just_enough_requirements_management_where_software_development_meets_marketing/level_of_requirements_detail.html";
ix++;
qfilename[ix] = "authors/alan_m_davis/just_enough_requirements_management_where_software_development_meets_marketing/lists_of_requirements.html";
ix++;
qfilename[ix] = "authors/alan_m_davis/just_enough_requirements_management_where_software_development_meets_marketing/requirements_elicitation_triage_and_specification.html";
ix++;
qfilename[ix] = "authors/richard_dawkins/the_god_delusion/evolutionary_drive_towards_complexity.html";
ix++;
qfilename[ix] = "authors/tom_demarco_and_timothy_lister/waltzing_with_bears_managing_risk_on_software_projects/belief_in_impossible_things.html";
ix++;
qfilename[ix] = "authors/tom_demarco_peter_hruschka_tim_lister_steve_mcmenamin_james_robertson_and_suzanne_robertson/adrenaline_junkies_and_template_zombies_understanding_patterns_of_project_behavior/template_zombies.html";
ix++;
qfilename[ix] = "authors/demarco_tom_hruschka_peter_lister_tim_mcmenamin_steve_robertson_james_and_suzanne_robertson/adrenaline_junkies_and_template_zombies_understanding_patterns_of_project_behavior/paper_mill.html";
ix++;
qfilename[ix] = "authors/ken_dymond/a_guide_to_the_cmm_understanding_the_capability_maturity_model_for_software/the_power_of_thought.html";
ix++;
qfilename[ix] = "authors/albert_einstein/unknown/simplicity_and_complexity.html";
ix++;
qfilename[ix] = "authors/albert_einstein/the_world_as_i_see_it/to_give_in_the_same_measure.html";
ix++;
qfilename[ix] = "authors/albert_einstein/on_the_method_of_theoretical_physics/the_supreme_goal_of_all_theory.html";
ix++;
qfilename[ix] = "authors/ralph_waldo_emerson/essential_writings_of_ralph_waldo_emerson/a_foolish_consistency.html";
ix++;
qfilename[ix] = "authors/f_scott_fitzgerald/the_crackup/a_firstrate_intelligence.html";
ix++;
qfilename[ix] = "authors/henry_ford/unknown/faster_horses.html";
ix++;
qfilename[ix] = "authors/e_m_forster/abinger_harvest/wriggling.html";
ix++;
qfilename[ix] = "authors/e_m_forster/howards_end/only_connect.html";
ix++;
qfilename[ix] = "authors/e_m_forster/howards_end/the_rainbow_bridge.html";
ix++;
qfilename[ix] = "authors/benjamin_franklin/unknown/education_and_genius.html";
ix++;
qfilename[ix] = "authors/john_kenneth_galbraith/unknown/conventional_views.html";
ix++;
qfilename[ix] = "authors/tom_gilb/dare_to_be_excellent_case_studies_of_software_engineering_practices_that_worked/underlying_intent_of_process_improvement.html";
ix++;
qfilename[ix] = "authors/tom_gilb/principles_of_software_engineering_management/software_more_than_code.html";
ix++;
qfilename[ix] = "authors/robert_l_glass/facts_and_fallacies_of_software_engineering/rigorous_software_inspections.html";
ix++;
qfilename[ix] = "authors/john_guillebaud/the_independent/climate_changers.html";
ix++;
qfilename[ix] = "authors/dashiell_hammett/the_dain_curse/a_dizzy_business.html";
ix++;
qfilename[ix] = "authors/dashiell_hammett/the_dain_curse/successful_planning.html";
ix++;
qfilename[ix] = "authors/sydney_harris/unknown/the_change_dilemma.html";
ix++;
qfilename[ix] = "authors/paul_heckel/the_elements_of_friendly_software_design/software_designer_as_communications_artist.html";
ix++;
qfilename[ix] = "authors/jim_highsmith/agile_software_development_ecosystems/value_of_coding_and_testing.html";
ix++;
qfilename[ix] = "authors/watts_humphrey/managing_the_software_process/key_software_problems.html";
ix++;
qfilename[ix] = "authors/watts_humphrey/managing_the_software_process/magic_answers_to_software_crisis.html";
ix++;
qfilename[ix] = "authors/watts_humphrey/managing_the_software_process/starting_with_firm_requirements.html";
ix++;
qfilename[ix] = "authors/watts_humphrey/managing_the_software_process/talented_people.html";
ix++;
qfilename[ix] = "authors/watts_humphrey/winning_with_software_an_executive_strategy/herding_software_engineers.html";
ix++;
qfilename[ix] = "authors/michael_innes/the_seven_suspects/merely_a_muddle.html";
ix++;
qfilename[ix] = "authors/thomas_jefferson/unknown/unintelligible_propositions.html";
ix++;
qfilename[ix] = "authors/scott_jenson/the_simplicity_shift_innovative_design_tactics_in_a_corporate_world/a_simplicity_shift.html";
ix++;
qfilename[ix] = "authors/scott_jenson/the_simplicity_shift_innovative_design_tactics_in_a_corporate_world/simplicity_as_a_design_goal.html";
ix++;
qfilename[ix] = "authors/scott_jenson/the_simplicity_shift_innovative_design_tactics_in_a_corporate_world/user_interfaces_dont_exist.html";
ix++;
qfilename[ix] = "authors/steve_jobs/business_week/people_dont_know_what_they_want_until_you_show_it_to_them.html";
ix++;
qfilename[ix] = "authors/steve_jobs/cmmi_guidelines_for_process_integration_and_product_improvement/design_is_the_fundamental_soul_of_a_humanmade_creation.html";
ix++;
qfilename[ix] = "authors/steve_jobs/insanely_great_the_life_and_times_of_macintosh_the_computer_that_changed_everything/the_underlying_principle_of_the_problem.html";
ix++;
qfilename[ix] = "authors/steve_jobs/macworld_keynote/where_the_puck_is_going_to_be.html";
ix++;
qfilename[ix] = "authors/alan_kay/the_simplicity_shift_innovative_design_tactics_in_a_corporate_world/simple_things_should_be_simple.html";
ix++;
qfilename[ix] = "authors/beverly_kaye_and_sharon_jordanevans/love_em_or_lose_em_getting_good_people_to_stay/satisfied_employees_are_in_the_know.html";
ix++;
qfilename[ix] = "authors/eamonn_kelly/powerful_times_rising_to_the_challenge_of_our_uncertain_world/the_fragile_constructs_of_history.html";
ix++;
qfilename[ix] = "authors/john_f_kennedy/commencement_address_at_yale_university/comforts_of_opinion.html";
ix++;
qfilename[ix] = "authors/martin_luther_king_jr/unknown/ends_for_which_we_live.html";
ix++;
qfilename[ix] = "authors/martin_luther_king_jr/unknown/ten_thousand_fools_proclaim_themselves.html";
ix++;
qfilename[ix] = "authors/martin_luther_king_jr/unknown/the_arc_of_history.html";
ix++;
qfilename[ix] = "authors/martin_luther_king_jr/civil_rights_march_on_washington_august_28/unarmed_truth_and_unconditional_love.html";
ix++;
qfilename[ix] = "authors/martin_luther_king_jr/remaining_awake_through_a_great_revolution/single_garment_of_destiny.html";
ix++;
qfilename[ix] = "authors/benjamin_l_kovitz/practical_software_requirements_a_manual_of_content_and_style/design_patterns.html";
ix++;
qfilename[ix] = "authors/benjamin_l_kovitz/practical_software_requirements_a_manual_of_content_and_style/solution_reuse.html";
ix++;
qfilename[ix] = "authors/bob_lewis/is_survival_guide/extensible_systems.html";
ix++;
qfilename[ix] = "authors/bob_lewis/is_survival_guide/good_mission_statements.html";
ix++;
qfilename[ix] = "authors/peter_van_der_linden/not_just_java/java.html";
ix++;
qfilename[ix] = "authors/michael_lopp/managing_humans_biting_and_humorous_tales_of_a_software_engineering_manager/delegation_is_a_slippery_slope.html";
ix++;
qfilename[ix] = "authors/michael_lopp/managing_humans_biting_and_humorous_tales_of_a_software_engineering_manager/involve_the_team_in_every_decision.html";
ix++;
qfilename[ix] = "authors/michael_lopp/managing_humans_biting_and_humorous_tales_of_a_software_engineering_manager/managers_cant_forget_how_to_develop_software.html";
ix++;
qfilename[ix] = "authors/michael_lopp/managing_humans_biting_and_humorous_tales_of_a_software_engineering_manager/onceaweek_meetings.html";
ix++;
qfilename[ix] = "authors/wynton_marsalis/moving_to_higher_ground_how_jazz_can_change_your_life/integrity_and_conviction.html";
ix++;
qfilename[ix] = "authors/wynton_marsalis/moving_to_higher_ground_how_jazz_can_change_your_life/linked_in_freedom.html";
ix++;
qfilename[ix] = "authors/wynton_marsalis/moving_to_higher_ground_how_jazz_can_change_your_life/moving_an_art_form_forward.html";
ix++;
qfilename[ix] = "authors/wynton_marsalis/moving_to_higher_ground_how_jazz_can_change_your_life/the_challenge_of_swing.html";
ix++;
qfilename[ix] = "authors/wynton_marsalis/moving_to_higher_ground_how_jazz_can_change_your_life/the_current_state_of_our_democracy.html";
ix++;
qfilename[ix] = "authors/wynton_marsalis/moving_to_higher_ground_how_jazz_can_change_your_life/the_philosophy_of_jazz.html";
ix++;
qfilename[ix] = "authors/wynton_marsalis/moving_to_higher_ground_how_jazz_can_change_your_life/the_power_of_art.html";
ix++;
qfilename[ix] = "authors/wynton_marsalis/moving_to_higher_ground_how_jazz_can_change_your_life/the_undisputed_sovereignty_of_the_human_being.html";
ix++;
qfilename[ix] = "authors/wynton_marsalis/moving_to_higher_ground_how_jazz_can_change_your_life/their_job_was_inventing_music.html";
ix++;
qfilename[ix] = "authors/groucho_marx/unknown/a_book_is_a_mans_best_friend.html";
ix++;
qfilename[ix] = "authors/margaret_mead/unknown/changing_the_world.html";
ix++;
qfilename[ix] = "authors/margaret_mead/unknown/quality_of_children_vs_quantity.html";
ix++;
qfilename[ix] = "authors/h_l_mencken/prejudices_second_series/easy_solutions.html";
ix++;
qfilename[ix] = "authors/h_l_mencken/minority_report_hl_menckens_notebooks/we_must_respect_the_other_fellows_religion.html";
ix++;
qfilename[ix] = "authors/h_l_mencken/prejudices_first_series/every_third_american.html";
ix++;
qfilename[ix] = "authors/john_stuart_mill/unknown/intellectual_debate.html";
ix++;
qfilename[ix] = "authors/henry_miller/big_sur_and_the_oranges_of_hieronymus_bosch/enemies_of_art_and_artist.html";
ix++;
qfilename[ix] = "authors/henry_miller/stand_still_like_the_hummingbird/plot_plan_calculate_or_postulate.html";
ix++;
qfilename[ix] = "authors/henry_mintzberg/in_search_of_excellence_lessons_from_americas_bestrun_companies/management_intuition.html";
ix++;
qfilename[ix] = "authors/james_m_morgan_and_jeffrey_k_liker/the_toyota_product_development_system_integrating_people_process_and_technology/leaders_are_the_primary_source_of_energy.html";
ix++;
qfilename[ix] = "authors/james_m_morgan_and_jeffrey_k_liker/the_toyota_product_development_system_integrating_people_process_and_technology/role_of_managers.html";
ix++;
qfilename[ix] = "authors/james_m_morgan_and_jeffrey_k_liker/the_toyota_product_development_system_integrating_people_process_and_technology/the_toyota_chief_engineer.html";
ix++;
qfilename[ix] = "authors/gilbert_murray/five_stages_of_greek_religion/hard_discipline_of_reasonableness_and_honesty.html";
ix++;
qfilename[ix] = "authors/jakob_nielsen/designing_web_usability_the_practice_of_simplicity/intranet_maintenance.html";
ix++;
qfilename[ix] = "authors/barack_obama/2009_inaugral_address/the_makers_of_things.html";
ix++;
qfilename[ix] = "authors/barack_obama/inaugral_address/a_return_to_these_truths.html";
ix++;
qfilename[ix] = "authors/ray_oldenburg/the_great_good_place/the_third_place.html";
ix++;
qfilename[ix] = "authors/tom_peters_and_robert_h_waterman_jr/in_search_of_excellence_lessons_from_americas_bestrun_companies/freedom_of_expression_in_business.html";
ix++;
qfilename[ix] = "authors/tom_peters_and_robert_h_waterman_jr/in_search_of_excellence_lessons_from_americas_bestrun_companies/we_like_to_think_of_ourselves_as_winners.html";
ix++;
qfilename[ix] = "authors/mary_poppendieck_and_tom_poppendieck/implementing_lean_software_development_from_concept_to_cash/puzzling_aspect_of_waterfall_development.html";
ix++;
qfilename[ix] = "authors/mary_poppendieck_and_tom_poppendieck/implementing_lean_software_development_from_concept_to_cash/the_most_fundamental_lean_measurement_is_cycle_time.html";
ix++;
qfilename[ix] = "authors/mary_poppendieck_and_tom_poppendieck/lean_software_development_an_agile_toolkit/evolving_system_structures.html";
ix++;
qfilename[ix] = "authors/jon_postel/transmission_control_protocol_request_for_comments_rfc_793/postels_law.html";
ix++;
qfilename[ix] = "authors/eric_s_raymond/the_cathedral_and_the_bazaar_musings_on_linux_and_open_source_by_an_accidental_revolutionary/open_source_development_styles.html";
ix++;
qfilename[ix] = "authors/tom_robbins/gracie_goes_to_schooner_school/the_world_is_a_wonderfully_weird_place.html";
ix++;
qfilename[ix] = "authors/suzanne_robertson_and_james_robertson/mastering_the_requirements_process/active_requirements_analysis.html";
ix++;
qfilename[ix] = "authors/bertrand_russell/unknown/men_fear_thought.html";
ix++;
qfilename[ix] = "authors/bertrand_russell/is_there_a_god/the_celestial_teapot.html";
ix++;
qfilename[ix] = "authors/carl_sagan_and_ann_druyan/shadows_of_forgotten_ancestors_a_search_for_who_we_are/apes_and_humans.html";
ix++;
qfilename[ix] = "authors/carl_sagan_and_ann_druyan/shadows_of_forgotten_ancestors_a_search_for_who_we_are/chimps_and_humans.html";
ix++;
qfilename[ix] = "authors/george_santayana/the_life_of_reason_reason_in_common_sense/progress_depends_on_retentiveness.html";
ix++;
qfilename[ix] = "authors/albert_schweitzer/leading_quietly_an_unorthodox_guide_to_doing_the_right_thing/small_and_obscure_deeds.html";
ix++;
qfilename[ix] = "authors/peter_senge/the_fifth_discipline_the_art_and_practice_of_the_learning_organization/learning_from_experience.html";
ix++;
qfilename[ix] = "authors/george_bernard_shaw/back_to_methuselah/i_dream_things_that_never_were.html";
ix++;
qfilename[ix] = "authors/joel_spolsky/joel_on_software/deferred_design_decisions.html";
ix++;
qfilename[ix] = "authors/joel_spolsky/joel_on_software/desirable_employee_attributes.html";
ix++;
qfilename[ix] = "authors/bruce_springsteen/rolling_stone_2007/a_long_conversation.html";
ix++;
qfilename[ix] = "authors/bruce_springsteen/rolling_stone_2009jan05/the_trick_in_keeping_bands_together.html";
ix++;
qfilename[ix] = "authors/dennis_stauffer/thinking_clockwise_a_field_guide_for_the_innovative_leader/the_columbia_disaster.html";
ix++;
qfilename[ix] = "authors/matthew_stewart/the_management_myth_why_the_experts_keep_getting_it_wrong/a_work_ethic_gone_mad.html";
ix++;
qfilename[ix] = "authors/matthew_stewart/the_management_myth_why_the_experts_keep_getting_it_wrong/behind_the_times.html";
ix++;
qfilename[ix] = "authors/matthew_stewart/the_management_myth_why_the_experts_keep_getting_it_wrong/preparing_managers_to_manage.html";
ix++;
qfilename[ix] = "authors/matthew_stewart/the_management_myth_why_the_experts_keep_getting_it_wrong/relieving_ignorance.html";
ix++;
qfilename[ix] = "authors/robert_townsend/up_the_organization/reorganizing.html";
ix++;
qfilename[ix] = "authors/mark_twain/unknown/do_the_right_thing.html";
ix++;
qfilename[ix] = "authors/john_updike/selfconsciousness_memoirs/dreams_come_true.html";
ix++;
qfilename[ix] = "authors/thomas_j_watson_jr/unknown/those_sharp_scratchy_harsh_almost_unpleasant_guys.html";
ix++;
qfilename[ix] = "authors/gerald_weinberg/the_psychology_of_computer_programming/elimination_of_programmers.html";
ix++;
qfilename[ix] = "authors/alfred_north_whitehead/unknown/the_art_of_progress.html";
ix++;
qfilename[ix] = "authors/ken_wilber/collected_works_of_ken_wilber_volume_8/everybody_has_some_important_pieces_of_the_truth.html";
ix++;
qfilename[ix] = "authors/ken_wilber/the_eye_of_spirit_an_integral_vision_for_a_world_gone_slightly_mad/art_and_spirit.html";
ix++;
qfilename[ix] = "authors/ken_wilber/the_integral_vision/all_the_worlds_cultures_now_available_to_us.html";
ix++;
qfilename[ix] = "authors/ken_wilber/the_integral_vision/levels_of_development.html";
ix++;
qfilename[ix] = "authors/ken_wilber/beliefnet/a_short_and_simple_list.html";
ix++;
qfilename[ix] = "authors/ken_wilber/beliefnet/an_integral_god.html";
ix++;
qfilename[ix] = "authors/ken_wilber/beliefnet/homophobia.html";
ix++;
qfilename[ix] = "authors/ken_wilber/beliefnet/the_beautiful_the_good_and_the_true.html";
ix++;
qfilename[ix] = "authors/tom_wolfe/the_kandykolored_tangerineflake_streamline_baby/what_youre_missing_is_the_beat.html";
ix++;
qfilename[ix] = "authors/jim_womack/eletter/lean.html";
ix++;
qfilename[ix] = "authors/frank_lloyd_wright/unknown/price_of_success.html";
ix++;
qfilename[ix] = "authors/edward_yourdon/decline_and_fall_of_the_american_programmer/no_silver_bullet.html";
ix++;
qfilename[ix] = "authors/edward_yourdon/decline_and_fall_of_the_american_programmer/sei_maturity_models.html";
ix++;

var max = ix;
  