/*
 * CatChangeScreen.java
 *
 * Created on March 19, 2004, 5:16 AM
 */

package com.powersurgepub.iwisdom;

  import com.powersurgepub.iwisdom.data.*;
  import javax.swing.*;

/**
 *
 * @author  hbowie
 */
public class CatChangeScreen 
    extends javax.swing.JDialog {
     
  private   java.awt.Frame        parent;
  private   iWisdomCommon          td;
  private   CategoryList          findCategories     = new CategoryList();
  private   CategoryList          replaceCategories  = new CategoryList();
  
  /** 
    Creates new form CatChangeScreen 
   */
  public CatChangeScreen(java.awt.Frame parent, boolean modal, iWisdomCommon td) {
    super (parent, modal);
    this.parent = parent;
    this.td = td;
    findCategories.addAll (td.getCategories());
    // findCategories.setSelectedItem (td.getCategories().getSelectedItem());
    replaceCategories.addAll (td.getCategories());
    // replaceCategories.setSelectedItem (td.getCategories().getSelectedItem());
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    findLabel = new javax.swing.JLabel();
    findComboBox = new javax.swing.JComboBox();
    replaceLabel = new javax.swing.JLabel();
    replaceComboBox = new javax.swing.JComboBox();
    replaceButton = new javax.swing.JButton();
    cancelButton = new javax.swing.JButton();
    buttonSpacerLabel = new javax.swing.JLabel();

    setTitle("Replace Category");
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        closeDialog(evt);
      }
    });
    getContentPane().setLayout(new java.awt.GridBagLayout());

    findLabel.setText("Existing Category:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.ipadx = 2;
    gridBagConstraints.ipady = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 0.2;
    gridBagConstraints.weighty = 0.1;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    getContentPane().add(findLabel, gridBagConstraints);

    findCategories.setComboBox(findComboBox);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 2;
    gridBagConstraints.ipady = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 0.4;
    gridBagConstraints.weighty = 0.1;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    getContentPane().add(findComboBox, gridBagConstraints);

    replaceLabel.setText("New Category:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.ipadx = 2;
    gridBagConstraints.ipady = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 0.2;
    gridBagConstraints.weighty = 0.1;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    getContentPane().add(replaceLabel, gridBagConstraints);

    replaceComboBox.setEditable(true);
    replaceCategories.setComboBox (replaceComboBox);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 2;
    gridBagConstraints.ipady = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 0.4;
    gridBagConstraints.weighty = 0.1;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    getContentPane().add(replaceComboBox, gridBagConstraints);

    replaceButton.setText("Add/Replace All");
    replaceButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        replaceButtonActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 2;
    gridBagConstraints.ipady = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 0.2;
    gridBagConstraints.weighty = 0.1;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    getContentPane().add(replaceButton, gridBagConstraints);

    cancelButton.setText("   Cancel    ");
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelButtonActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 2;
    gridBagConstraints.ipady = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 0.2;
    gridBagConstraints.weighty = 0.1;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    getContentPane().add(cancelButton, gridBagConstraints);

    buttonSpacerLabel.setText("                         ");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 2;
    gridBagConstraints.ipady = 2;
    gridBagConstraints.weightx = 0.2;
    gridBagConstraints.weighty = 0.1;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    getContentPane().add(buttonSpacerLabel, gridBagConstraints);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void replaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceButtonActionPerformed
    String find = (String)(findCategories.getSelectedItem());
    String replace = (String)(replaceCategories.getSelectedItem());
    int mods = td.replaceCategory (find, replace);
    setVisible (false);
    dispose();
    JOptionPane.showMessageDialog(parent,
      String.valueOf (mods) 
          + " items changed",
      "Category Replacement Results",
      JOptionPane.INFORMATION_MESSAGE);
  }//GEN-LAST:event_replaceButtonActionPerformed

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    setVisible (false);
    dispose();
  }//GEN-LAST:event_cancelButtonActionPerformed
  
  /** Closes the dialog */
  private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
    setVisible(false);
    dispose();
  }//GEN-LAST:event_closeDialog
  
  /**
   * @param args the command line arguments
   */
  // public static void main(String args[]) {
  //   new CatChangeScreen(new javax.swing.JFrame(), true).show();
  // }
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel buttonSpacerLabel;
  private javax.swing.JButton cancelButton;
  private javax.swing.JComboBox findComboBox;
  private javax.swing.JLabel findLabel;
  private javax.swing.JButton replaceButton;
  private javax.swing.JComboBox replaceComboBox;
  private javax.swing.JLabel replaceLabel;
  // End of variables declaration//GEN-END:variables
  
}
