/*
 * PrefsWindow.java
 *
 * Created on August 5, 2007, 8:58 AM
 */

package com.powersurgepub.iwisdom;

  import com.powersurgepub.psfiles.FilePrefs;
  import com.powersurgepub.psdatalib.ui.*;
  import com.powersurgepub.psutils.*;
  import com.powersurgepub.iwisdom.disk.*;
  import com.powersurgepub.xos2.*;
  import javax.swing.*;

/**
 *
 * @author  hbowie
 */
public class PrefsWindow 
  extends javax.swing.JFrame
    implements WindowToManage {
  
  private iWisdomCommon      td;
  
  private XOS               xos = XOS.getShared();
  
  private ProgramVersion    programVersion = ProgramVersion.getShared();
  
  private boolean           setupComplete = false;
  
  private CommonPrefs       commonPrefs;
  private GeneralPrefs      generalPrefs;
  private DisplayPrefs      displayPrefs;
  private ViewPrefs         viewPrefs;
  private TransferPrefs     transferPrefs;
  private FilePrefs       backupPrefs;
  
  /** Creates new form PrefsWindow */
  public PrefsWindow(iWisdomCommon td) {
    this.td = td;
    initComponents();
    
    this.setTitle (Home.getShared().getProgramName() + " Preferences");
    this.setBounds (100, 100, 600, 540);

    commonPrefs = CommonPrefs.getShared();
    prefsTabs.addTab("Common", commonPrefs);
    
    generalPrefs = new GeneralPrefs (td, this);
    prefsTabs.addTab("General", generalPrefs);
    
    displayPrefs = new DisplayPrefs (td, this);
    prefsTabs.addTab ("Display", displayPrefs);
    
    viewPrefs = new ViewPrefs(td, this);
    prefsTabs.addTab ("Views", viewPrefs);

    transferPrefs = new TransferPrefs(td, this);
    prefsTabs.addTab ("Transfer", transferPrefs);
    
    backupPrefs = FilePrefs.getShared(td);
    prefsTabs.addTab ("Backups", backupPrefs);
    
    setupComplete = true;
  }
  
  public GeneralPrefs getGeneralPrefs () {
    return generalPrefs;
  }
  
  public ViewPrefs getViewPrefs () {
    return viewPrefs;
  }

  public TransferPrefs getTransferPrefs() {
    return transferPrefs;
  }
  
  /**
    Prepares the tab for processing of newly opened file.
   
    @param store Disk Store object for the file.
   */
  public void filePrep (WisdomDiskStore store) {
    // No file information used on the Prefs Tab
  }
  
  /**
    Prepare to switch tabs and show this one.
   */
  private void showThisTab () {
    td.switchTabs();
  }
  
  public void displayItem() {
  }  
  
  public boolean modIfChanged() {
    return false;
  }  
  
  public void switchTabs () {
    
  }
  
  private void warnRelaunch() {
    JOptionPane.showMessageDialog (
        td.tabs,
        "You may need to Quit and relaunch "
            + XOS.getShared().getProgramName()
            + " for your preferences to take effect.",
        "Relaunch Warning",
        JOptionPane.WARNING_MESSAGE);
  }

  public void savePrefs() {
    commonPrefs.savePrefs();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    prefsTabs = new javax.swing.JTabbedPane();

    addComponentListener(new java.awt.event.ComponentAdapter() {
      public void componentHidden(java.awt.event.ComponentEvent evt) {
        formComponentHidden(evt);
      }
    });
    getContentPane().add(prefsTabs, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
  WindowMenuManager.getShared().hide(this);
}//GEN-LAST:event_formComponentHidden
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTabbedPane prefsTabs;
  // End of variables declaration//GEN-END:variables
  
}
